using System.Security.Cryptography;
using System.Text;

namespace FMS.Infrastructure.Auth;

/// <summary>
/// Hashes opaque tokens (password reset, farm invitations) before they are
/// persisted, so a database leak does not hand out usable links.
///
/// SHA-256 without a salt is sufficient here because these tokens are
/// high-entropy random values generated by the server, not user-chosen secrets,
/// so there is nothing to brute-force or rainbow-table.
/// </summary>
internal static class TokenHasher
{
    public static string Hash(string token)
    {
        var bytes = SHA256.HashData(Encoding.UTF8.GetBytes(token));
        return Convert.ToHexString(bytes).ToLowerInvariant();
    }
}
