using System.Text;
using FMS.Infrastructure.Files;

namespace FMS.Domain.Tests;

/// <summary>
/// Behaviour of the local-disk provider, which is the default outside production.
/// </summary>
public class FileStorageServiceTests : IDisposable
{
    private static readonly string[] AllowedExtensions = [".jpg", ".png"];
    private const long MaxBytes = 1024 * 1024;

    private readonly string _root = Path.Combine(Path.GetTempPath(), $"fms-storage-{Guid.NewGuid():N}");

    private FileStorageService CreateService() => new(_root);

    private static MemoryStream Content(string text = "hello") => new(Encoding.UTF8.GetBytes(text));

    public void Dispose()
    {
        if (Directory.Exists(_root))
            Directory.Delete(_root, recursive: true);
    }

    [Fact]
    public async Task SaveAsync_StoresUnderTheRequestedFolder_AndReportsAKey()
    {
        var service = CreateService();

        var result = await service.SaveAsync("farms/f1/animals/a1/images", Content(), "photo.JPG", "image/jpeg", MaxBytes, AllowedExtensions);

        Assert.True(result.IsSuccess);
        Assert.StartsWith("farms/f1/animals/a1/images/", result.Value!.StoragePath);
        // Extension is normalised and the stored name is random, not the client's.
        Assert.EndsWith(".jpg", result.Value.StoragePath);
        Assert.DoesNotContain("photo", result.Value.StoragePath, StringComparison.OrdinalIgnoreCase);
        Assert.True(await service.ExistsAsync(result.Value.StoragePath));
    }

    [Fact]
    public async Task SaveAsync_RejectsEmptyOversizedAndDisallowedFiles()
    {
        var service = CreateService();

        Assert.False((await service.SaveAsync("f", new MemoryStream(), "a.jpg", "image/jpeg", MaxBytes, AllowedExtensions)).IsSuccess);
        Assert.False((await service.SaveAsync("f", Content(new string('x', 32)), "a.jpg", "image/jpeg", 8, AllowedExtensions)).IsSuccess);
        Assert.False((await service.SaveAsync("f", Content(), "malware.exe", "application/octet-stream", MaxBytes, AllowedExtensions)).IsSuccess);
    }

    [Fact]
    public async Task OpenReadAsync_RoundTripsTheStoredBytes_AndDeleteRemovesThem()
    {
        var service = CreateService();
        var saved = await service.SaveAsync("docs", Content("payload"), "note.txt", "text/plain", MaxBytes, [".txt"]);
        var key = saved.Value!.StoragePath;

        using (var reader = new StreamReader(await service.OpenReadAsync(key)))
            Assert.Equal("payload", await reader.ReadToEndAsync());

        await service.DeleteAsync(key);
        Assert.False(await service.ExistsAsync(key));

        // Deleting a missing key is a no-op, not a throw.
        await service.DeleteAsync(key);
    }

    [Fact]
    public async Task StorageKeys_CannotEscapeTheUploadsRoot()
    {
        var service = CreateService();
        Directory.CreateDirectory(_root);
        var secret = Path.Combine(Path.GetTempPath(), $"fms-secret-{Guid.NewGuid():N}.txt");
        await File.WriteAllTextAsync(secret, "should not be readable");

        try
        {
            // Keys are generated by this service, but they are persisted and replayed,
            // so a traversing value must never resolve outside the root.
            var escaped = Path.Combine("..", Path.GetFileName(secret));

            Assert.False(await service.ExistsAsync(escaped));
            await Assert.ThrowsAsync<FileNotFoundException>(() => service.OpenReadAsync(escaped));
        }
        finally
        {
            File.Delete(secret);
        }
    }

    [Fact]
    public async Task LocalStorage_DoesNotPretendToIssuePresignedUrls()
    {
        var service = CreateService();
        var saved = await service.SaveAsync("f", Content(), "a.jpg", "image/jpeg", MaxBytes, AllowedExtensions);

        Assert.False(service.SupportsPresignedUrls);

        // Callers must fall back to streaming instead; a failure here is the signal.
        var presigned = await service.GetPresignedDownloadUrlAsync(saved.Value!.StoragePath, "a.jpg");
        Assert.False(presigned.IsSuccess);
    }
}
