import React, { useCallback, useEffect, useState } from 'react';
import { Button, Card, Form, Input, InputNumber, Modal, Popconfirm, Select, Space, Table, Tabs, message } from 'antd';
import { PlusOutlined } from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import dayjs from 'dayjs';
import { inventoryApi } from '../../api/inventory';
import { customersApi } from '../../api/customers';
import { getApiError } from '../../api/farmApi';
import type { Customer, CustomerSale, InventoryItem } from '../../types';

const CustomersPage: React.FC = () => {
  const [customers, setCustomers] = useState<Customer[]>([]); const [items, setItems] = useState<InventoryItem[]>([]); const [sales, setSales] = useState<CustomerSale[]>([]); const [loading, setLoading] = useState(false); const [customerOpen, setCustomerOpen] = useState(false); const [saleOpen, setSaleOpen] = useState(false); const [editing, setEditing] = useState<Customer | null>(null); const [form] = Form.useForm(); const [saleForm] = Form.useForm();
  const load = useCallback(async () => { setLoading(true); try { const [c, i, s] = await Promise.all([customersApi.list({ page: 1, pageSize: 100 }), inventoryApi.list({ page: 1, pageSize: 100 }), customersApi.sales({ page: 1, pageSize: 100 })]); setCustomers(c.data.items); setItems(i.data.items); setSales(s.data.items); } catch (err) { message.error(getApiError(err)); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const saveCustomer = async () => { try { const value = await form.validateFields(); if (editing) await customersApi.update(editing.id, value); else await customersApi.create(value); setCustomerOpen(false); message.success('Customer saved'); void load(); } catch (err) { if (!(err as { errorFields?: unknown }).errorFields) message.error(getApiError(err)); } };
  const saveSale = async () => { try { const value = await saleForm.validateFields(); await customersApi.createSale({ ...value, saleDate: value.saleDate?.format('YYYY-MM-DD') }); setSaleOpen(false); message.success('Sale recorded, stock reduced, and income linked'); void load(); } catch (err) { if (!(err as { errorFields?: unknown }).errorFields) message.error(getApiError(err)); } };
  const columns: ColumnsType<Customer> = [{ title: 'Customer', dataIndex: 'name' }, { title: 'Contact', dataIndex: 'contactInfo', render: (v?: string) => v || '-' }, { title: 'Sales', dataIndex: 'saleCount' }, { title: 'Total sales', dataIndex: 'totalSales', render: (v: number) => `$${v.toFixed(2)}` }, { title: 'Actions', render: (_, r) => <Space><Button size="small" onClick={() => { setEditing(r); form.setFieldsValue(r); setCustomerOpen(true); }}>Edit</Button><Popconfirm title="Delete this customer?" onConfirm={async () => { try { await customersApi.remove(r.id); message.success('Customer deleted'); void load(); } catch (err) { message.error(getApiError(err)); } }}><Button size="small" danger>Delete</Button></Popconfirm></Space> }];
  const saleColumns: ColumnsType<CustomerSale> = [{ title: 'Date', dataIndex: 'saleDate', render: (v: string) => dayjs(v).format('YYYY-MM-DD') }, { title: 'Customer', dataIndex: 'customerName' }, { title: 'Item', dataIndex: 'inventoryItemName' }, { title: 'Quantity', dataIndex: 'quantity', render: (v: number, r) => `${v} ${r.unit}` }, { title: 'Total amount', dataIndex: 'totalAmount', render: (v: number) => `$${v.toFixed(2)}` }];
  return <Card title="Customers" extra={<Space><Button icon={<PlusOutlined />} onClick={() => { setEditing(null); form.resetFields(); setCustomerOpen(true); }}>Add customer</Button><Button type="primary" icon={<PlusOutlined />} onClick={() => { saleForm.resetFields(); saleForm.setFieldsValue({ saleDate: dayjs() }); setSaleOpen(true); }}>Record sale</Button></Space>}><Tabs items={[{ key: 'customers', label: 'Directory', children: <Table rowKey="id" columns={columns} dataSource={customers} loading={loading} pagination={{ pageSize: 10 }} /> }, { key: 'sales', label: 'Sales history', children: <Table rowKey="id" columns={saleColumns} dataSource={sales} loading={loading} pagination={{ pageSize: 10 }} /> }]} /><Modal title={editing ? 'Edit customer' : 'Add customer'} open={customerOpen} onOk={() => void saveCustomer()} onCancel={() => setCustomerOpen(false)} destroyOnClose><Form form={form} layout="vertical"><Form.Item name="name" label="Name" rules={[{ required: true }]}><Input maxLength={200} /></Form.Item><Form.Item name="contactInfo" label="Contact information"><Input.TextArea rows={3} maxLength={1000} /></Form.Item></Form></Modal><Modal title="Record customer sale" open={saleOpen} onOk={() => void saveSale()} onCancel={() => setSaleOpen(false)} destroyOnClose><Form form={saleForm} layout="vertical"><Form.Item name="customerId" label="Customer" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={customers.map(c => ({ value: c.id, label: c.name }))} /></Form.Item><Form.Item name="inventoryItemId" label="Inventory item" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={items.map(i => ({ value: i.id, label: `${i.name} (${i.quantity} ${i.unit} available)` }))} /></Form.Item><Space style={{ display: 'flex' }}><Form.Item name="quantity" label="Quantity" rules={[{ required: true }]}><InputNumber min={0.001} precision={3} /></Form.Item><Form.Item name="totalAmount" label="Total amount" rules={[{ required: true }]}><InputNumber min={0} precision={2} prefix="$" /></Form.Item></Space><Form.Item name="saleDate" label="Date" rules={[{ required: true }]}><Input type="date" /></Form.Item><Form.Item name="notes" label="Notes"><Input.TextArea rows={2} /></Form.Item></Form></Modal></Card>;
}; export default CustomersPage;
