import React, { useCallback, useEffect, useState } from 'react';
import { formatMoney } from '../../i18n/format';
import { Alert, Button, Card, Col, Row, Space, Statistic, Table, Tag } from 'antd';
import { DownloadOutlined, ReloadOutlined } from '@ant-design/icons';
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import type { ColumnsType } from 'antd/es/table';
import { inventoryApi } from '../../api/inventory';
import { getApiError } from '../../api/farmApi';
import type { InventoryLowStockAlert, InventoryReport, InventoryStockReportItem } from '../../types';
import { useTranslation } from 'react-i18next';

const downloadCsv = (filename: string, rows: string[][]) => {
  const csv = rows.map(row => row.map(value => `"${value.replace(/"/g, '""')}"`).join(',')).join('\n');
  const link = document.createElement('a'); link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8;' })); link.download = filename; link.click(); URL.revokeObjectURL(link.href);
};

const InventoryReportsPage: React.FC = () => {const { t } = useTranslation('inventory'); 
  const [report, setReport] = useState<InventoryReport | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); setError(null); try { setReport((await inventoryApi.report()).data); } catch (err) { setError(getApiError(err)); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const exportStock = () => { if (!report) return; downloadCsv('inventory-stock.csv', [['Item', 'Category', 'Unit', 'Quantity', 'Reorder Level', 'Unit Cost', 'Stock Value', 'Location'], ...report.currentStock.map(i => [i.itemName, i.category || '', i.unit, `${i.quantity}`, `${i.reorderLevel}`, `${i.unitCost}`, `${i.stockValue}`, i.location || ''])]); };
  const stockColumns: ColumnsType<InventoryStockReportItem> = [{ title: t('item'), dataIndex: 'itemName' }, { title: t('category'), dataIndex: 'category', render: (v?: string) => v || '-' }, { title: t('quantity'), dataIndex: 'quantity', render: (v: number, r) => <span>{v} {r.isLowStock && <Tag color="error">{t('low')}</Tag>}</span> }, { title: t('reorderLevel'), dataIndex: 'reorderLevel' }, { title: t('unitCost'), dataIndex: 'unitCost', render: (v: number) => formatMoney(v) }, { title: t('stockValue'), dataIndex: 'stockValue', render: (v: number) => formatMoney(v) }, { title: t('location'), dataIndex: 'location', render: (v?: string) => v || '-' }];
  const alertColumns: ColumnsType<InventoryLowStockAlert> = [{ title: t('item'), dataIndex: 'itemName' }, { title: t('quantity'), dataIndex: 'quantity', render: (v: number, r) => `${v} ${r.unit}` }, { title: t('reorderLevel'), dataIndex: 'reorderLevel' }, { title: t('shortfall'), dataIndex: 'shortfall', render: (v: number, r) => <strong style={{ color: '#cf1322' }}>{v} {r.unit}</strong> }, { title: t('location'), dataIndex: 'location', render: (v?: string) => v || '-' }];
  return <Space direction="vertical" size="large" style={{ width: '100%' }}>{error && <Alert type="error" showIcon message={error} closable onClose={() => setError(null)} />}<Card title={t('inventoryReports')} extra={<Space><Button icon={<ReloadOutlined />} onClick={() => void load()}>{t('refresh')}</Button><Button icon={<DownloadOutlined />} onClick={exportStock} disabled={!report}>{t('exportStockCsv')}</Button></Space>} loading={loading}><Row gutter={16}><Col xs={24} sm={8}><Statistic title={t('totalStockValue')} value={report?.totalStockValue ?? 0} precision={2} prefix="$" /></Col><Col xs={24} sm={8}><Statistic title={t('inventoryItems2')} value={report?.totalItems ?? 0} /></Col><Col xs={24} sm={8}><Statistic title={t('lowStockAlerts')} value={report?.lowStockItemCount ?? 0} valueStyle={{ color: report?.lowStockItemCount ? '#cf1322' : undefined }} /></Col></Row></Card><Card title={t('movementVolume')}><ResponsiveContainer width="100%" height={260}><BarChart data={report?.movementSummary ?? []}><CartesianGrid strokeDasharray="3 3" /><XAxis dataKey="movementTypeName" /><YAxis /><Tooltip /><Bar dataKey="quantity" fill="#1677ff" name="Quantity" /></BarChart></ResponsiveContainer></Card><Card title={t('lowStockAlerts')} extra={<Tag color={report?.lowStockItemCount ? 'error' : 'success'}>{report?.lowStockItemCount ?? 0} {t('items')}</Tag>}><Table rowKey="inventoryItemId" columns={alertColumns} dataSource={report?.lowStockAlerts ?? []} pagination={false} locale={{ emptyText: 'All inventory items are above their reorder levels.' }} /></Card><Card title={t('currentStock')} extra={<Button icon={<DownloadOutlined />} onClick={exportStock}>{t('exportCsv')}</Button>}><Table rowKey="inventoryItemId" columns={stockColumns} dataSource={report?.currentStock ?? []} pagination={{ pageSize: 10 }} /></Card></Space>;
}; export default InventoryReportsPage;
