import React, { useCallback, useEffect, useState } from 'react';
import { Button, Card, Col, DatePicker, Form, Input, InputNumber, Modal, Popconfirm, Row, Select, Space, Table, Tabs, message } from 'antd';
import { PlusOutlined, UploadOutlined } from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import { useNavigate } from 'react-router-dom';
import { formatDate, formatMoney } from '../../i18n/format';
import dayjs from 'dayjs';
import { inventoryApi } from '../../api/inventory';
import { suppliersApi } from '../../api/suppliers';
import { getApiError } from '../../api/farmApi';
import { expenseCategoriesApi, paymentMethodsApi } from '../../api/finance';
import LookupQuickAddSelect from '../../components/LookupQuickAddSelect';
import type { ExpenseCategory, InventoryItem, PaymentMethod, Supplier, SupplierPurchase } from '../../types';
import { useTranslation } from 'react-i18next';

const SuppliersPage: React.FC = () => {const { t } = useTranslation('inventory'); 
  const navigate = useNavigate();
  const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [items, setItems] = useState<InventoryItem[]>([]); const [purchases, setPurchases] = useState<SupplierPurchase[]>([]);
  const [loading, setLoading] = useState(false); const [supplierOpen, setSupplierOpen] = useState(false); const [purchaseOpen, setPurchaseOpen] = useState(false); const [editing, setEditing] = useState<Supplier | null>(null);
  const [form] = Form.useForm(); const [purchaseForm] = Form.useForm();
  const [categories, setCategories] = useState<ExpenseCategory[]>([]); const [methods, setMethods] = useState<PaymentMethod[]>([]);
  const load = useCallback(async () => { setLoading(true); try { const [s, i, p, ec, pm] = await Promise.all([suppliersApi.list({ page: 1, pageSize: 100 }), inventoryApi.list({ page: 1, pageSize: 100 }), suppliersApi.purchases({ page: 1, pageSize: 100 }), expenseCategoriesApi.list(), paymentMethodsApi.list()]); setSuppliers(s.data.items); setItems(i.data.items); setPurchases(p.data.items); setCategories(ec.data); setMethods(pm.data); } catch (err) { message.error(getApiError(err)); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const saveSupplier = async () => { try { const value = await form.validateFields(); if (editing) await suppliersApi.update(editing.id, value); else await suppliersApi.create(value); setSupplierOpen(false); message.success(t('supplierSaved')); void load(); } catch (err) { if (!(err as { errorFields?: unknown }).errorFields) message.error(getApiError(err)); } };
  const savePurchase = async () => { try { const value = await purchaseForm.validateFields(); await suppliersApi.createPurchase({ ...value, purchaseDate: value.purchaseDate?.toISOString() }); setPurchaseOpen(false); message.success(t('purchaseRecordedStockUpdatedAndExpenseLinked')); void load(); } catch (err) { if (!(err as { errorFields?: unknown }).errorFields) message.error(getApiError(err)); } };
  const columns: ColumnsType<Supplier> = [{ title: t('supplier'), dataIndex: 'name' }, { title: t('contact'), dataIndex: 'contactInfo', render: (v?: string) => v || '-' }, { title: t('productsSupplied'), dataIndex: 'productsSupplied', render: (v?: string) => v || '-' }, { title: t('purchases'), dataIndex: 'purchaseCount' }, { title: t('totalPurchased'), dataIndex: 'totalPurchased', render: (v: number) => formatMoney(v) }, { title: t('actions'), render: (_, r) => <Space><Button size="small" onClick={() => { setEditing(r); form.setFieldsValue(r); setSupplierOpen(true); }}>{t('edit')}</Button><Popconfirm title={t('deleteThisSupplier')} onConfirm={async () => { try { await suppliersApi.remove(r.id); message.success(t('supplierDeleted')); void load(); } catch (err) { message.error(getApiError(err)); } }}><Button size="small" danger>{t('delete')}</Button></Popconfirm></Space> }];
  const purchaseColumns: ColumnsType<SupplierPurchase> = [{ title: t('date'), dataIndex: 'purchaseDate', render: (v: string) => formatDate(v) }, { title: t('supplier'), dataIndex: 'supplierName' }, { title: t('item'), dataIndex: 'inventoryItemName' }, { title: t('quantity'), dataIndex: 'quantity', render: (v: number, r) => `${v} ${r.unit}` }, { title: t('totalCost'), dataIndex: 'totalCost', render: (v: number) => formatMoney(v) }];
  return <Card title={t('suppliers')} extra={<Space><Button icon={<UploadOutlined />} onClick={() => navigate('/dashboard/inventory/suppliers/import')}>{t('import')}</Button><Button icon={<PlusOutlined />} onClick={() => { setEditing(null); form.resetFields(); setSupplierOpen(true); }}>{t('addSupplier')}</Button><Button type="primary" icon={<PlusOutlined />} onClick={() => { purchaseForm.resetFields(); purchaseForm.setFieldsValue({ purchaseDate: dayjs() }); setPurchaseOpen(true); }}>{t('recordPurchase')}</Button></Space>}><Tabs items={[{ key: 'suppliers', label: t('directory'), children: <Table rowKey="id" columns={columns} dataSource={suppliers} loading={loading} pagination={{ pageSize: 10 }} /> }, { key: 'purchases', label: t('purchaseHistory'), children: <Table rowKey="id" columns={purchaseColumns} dataSource={purchases} loading={loading} pagination={{ pageSize: 10 }} /> }]} />
    <Modal title={editing ? t('editSupplier') : t('addSupplier')} open={supplierOpen} onOk={() => void saveSupplier()} onCancel={() => setSupplierOpen(false)} destroyOnClose><Form form={form} layout="vertical"><Form.Item name="name" label={t('name')} rules={[{ required: true }]}><Input maxLength={200} /></Form.Item><Form.Item name="contactInfo" label={t('contactInformation')}><Input.TextArea rows={2} maxLength={1000} /></Form.Item><Form.Item name="productsSupplied" label={t('productsSupplied')}><Input.TextArea rows={2} maxLength={2000} /></Form.Item></Form></Modal>
    <Modal title={t('recordSupplierPurchase')} open={purchaseOpen} onOk={() => void savePurchase()} onCancel={() => setPurchaseOpen(false)} destroyOnClose width={600}><Form form={purchaseForm} layout="vertical"><Form.Item name="supplierId" label={t('supplier')} rules={[{ required: true }]}><LookupQuickAddSelect kind="supplier" options={suppliers.map(s => ({ value: s.id, label: s.name }))} onCreated={() => load()} /></Form.Item><Form.Item name="inventoryItemId" label={t('inventoryItem')} rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={items.map(i => ({ value: i.id, label: `${i.name} (${i.unit})` }))} style={{ width: '100%' }} popupMatchSelectWidth={false} /></Form.Item><Row gutter={[16, 16]}><Col xs={24} sm={12}><Form.Item name="quantity" label={t('quantity')} rules={[{ required: true }]}><InputNumber min={0.001} precision={3} style={{ width: '100%' }} /></Form.Item></Col><Col xs={24} sm={12}><Form.Item name="totalCost" label={t('totalCost')} rules={[{ required: true }]}><InputNumber min={0} precision={2} prefix="$" style={{ width: '100%' }} /></Form.Item></Col></Row><Form.Item name="purchaseDate" label={t('date')} rules={[{ required: true }]}><DatePicker style={{ width: '100%' }} /></Form.Item><Form.Item name="expenseCategoryId" label={t('expenseCategoryOptional')}><LookupQuickAddSelect kind="expenseCategory" allowClear options={categories.map(c => ({ value: c.id, label: c.name }))} onCreated={() => load()} /></Form.Item><Form.Item name="paymentMethodId" label={t('paymentMethodOptional')}><LookupQuickAddSelect kind="paymentMethod" allowClear options={methods.map(m => ({ value: m.id, label: m.name }))} onCreated={() => load()} /></Form.Item><Form.Item name="notes" label={t('notes')}><Input.TextArea rows={2} /></Form.Item></Form></Modal>
  </Card>;
}; export default SuppliersPage;
