import React, { useCallback, useEffect, useState } from 'react';
import { Button, Card, Col, DatePicker, Form, Input, InputNumber, Modal, Popconfirm, Row, Select, Space, Table, Tabs, message } from 'antd';
import { PlusOutlined } from '@ant-design/icons';
import type { ColumnsType } from 'antd/es/table';
import dayjs from 'dayjs';
import { inventoryApi } from '../../api/inventory';
import { suppliersApi } from '../../api/suppliers';
import { getApiError } from '../../api/farmApi';
import type { InventoryItem, Supplier, SupplierPurchase } from '../../types';

const SuppliersPage: React.FC = () => {
  const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [items, setItems] = useState<InventoryItem[]>([]); const [purchases, setPurchases] = useState<SupplierPurchase[]>([]);
  const [loading, setLoading] = useState(false); const [supplierOpen, setSupplierOpen] = useState(false); const [purchaseOpen, setPurchaseOpen] = useState(false); const [editing, setEditing] = useState<Supplier | null>(null);
  const [form] = Form.useForm(); const [purchaseForm] = Form.useForm();
  const load = useCallback(async () => { setLoading(true); try { const [s, i, p] = await Promise.all([suppliersApi.list({ page: 1, pageSize: 100 }), inventoryApi.list({ page: 1, pageSize: 100 }), suppliersApi.purchases({ page: 1, pageSize: 100 })]); setSuppliers(s.data.items); setItems(i.data.items); setPurchases(p.data.items); } catch (err) { message.error(getApiError(err)); } finally { setLoading(false); } }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load(); }, 0); return () => window.clearTimeout(timer); }, [load]);
  const saveSupplier = async () => { try { const value = await form.validateFields(); if (editing) await suppliersApi.update(editing.id, value); else await suppliersApi.create(value); setSupplierOpen(false); message.success('Supplier saved'); void load(); } catch (err) { if (!(err as { errorFields?: unknown }).errorFields) message.error(getApiError(err)); } };
  const savePurchase = async () => { try { const value = await purchaseForm.validateFields(); await suppliersApi.createPurchase({ ...value, purchaseDate: value.purchaseDate?.toISOString() }); setPurchaseOpen(false); message.success('Purchase recorded, stock updated, and expense linked'); void load(); } catch (err) { if (!(err as { errorFields?: unknown }).errorFields) message.error(getApiError(err)); } };
  const columns: ColumnsType<Supplier> = [{ title: 'Supplier', dataIndex: 'name' }, { title: 'Contact', dataIndex: 'contactInfo', render: (v?: string) => v || '-' }, { title: 'Products supplied', dataIndex: 'productsSupplied', render: (v?: string) => v || '-' }, { title: 'Purchases', dataIndex: 'purchaseCount' }, { title: 'Total purchased', dataIndex: 'totalPurchased', render: (v: number) => `$${v.toFixed(2)}` }, { title: 'Actions', render: (_, r) => <Space><Button size="small" onClick={() => { setEditing(r); form.setFieldsValue(r); setSupplierOpen(true); }}>Edit</Button><Popconfirm title="Delete this supplier?" onConfirm={async () => { try { await suppliersApi.remove(r.id); message.success('Supplier deleted'); void load(); } catch (err) { message.error(getApiError(err)); } }}><Button size="small" danger>Delete</Button></Popconfirm></Space> }];
  const purchaseColumns: ColumnsType<SupplierPurchase> = [{ title: 'Date', dataIndex: 'purchaseDate', render: (v: string) => dayjs(v).format('YYYY-MM-DD') }, { title: 'Supplier', dataIndex: 'supplierName' }, { title: 'Item', dataIndex: 'inventoryItemName' }, { title: 'Quantity', dataIndex: 'quantity', render: (v: number, r) => `${v} ${r.unit}` }, { title: 'Total cost', dataIndex: 'totalCost', render: (v: number) => `$${v.toFixed(2)}` }];
  return <Card title="Suppliers" extra={<Space><Button icon={<PlusOutlined />} onClick={() => { setEditing(null); form.resetFields(); setSupplierOpen(true); }}>Add supplier</Button><Button type="primary" icon={<PlusOutlined />} onClick={() => { purchaseForm.resetFields(); purchaseForm.setFieldsValue({ purchaseDate: dayjs() }); setPurchaseOpen(true); }}>Record purchase</Button></Space>}><Tabs items={[{ key: 'suppliers', label: 'Directory', children: <Table rowKey="id" columns={columns} dataSource={suppliers} loading={loading} pagination={{ pageSize: 10 }} /> }, { key: 'purchases', label: 'Purchase history', children: <Table rowKey="id" columns={purchaseColumns} dataSource={purchases} loading={loading} pagination={{ pageSize: 10 }} /> }]} />
    <Modal title={editing ? 'Edit supplier' : 'Add supplier'} open={supplierOpen} onOk={() => void saveSupplier()} onCancel={() => setSupplierOpen(false)} destroyOnClose><Form form={form} layout="vertical"><Form.Item name="name" label="Name" rules={[{ required: true }]}><Input maxLength={200} /></Form.Item><Form.Item name="contactInfo" label="Contact information"><Input.TextArea rows={2} maxLength={1000} /></Form.Item><Form.Item name="productsSupplied" label="Products supplied"><Input.TextArea rows={2} maxLength={2000} /></Form.Item></Form></Modal>
    <Modal title="Record supplier purchase" open={purchaseOpen} onOk={() => void savePurchase()} onCancel={() => setPurchaseOpen(false)} destroyOnClose width={600}><Form form={purchaseForm} layout="vertical"><Form.Item name="supplierId" label="Supplier" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={suppliers.map(s => ({ value: s.id, label: s.name }))} style={{ width: '100%' }} /></Form.Item><Form.Item name="inventoryItemId" label="Inventory item" rules={[{ required: true }]}><Select showSearch optionFilterProp="label" options={items.map(i => ({ value: i.id, label: `${i.name} (${i.unit})` }))} style={{ width: '100%' }} popupMatchSelectWidth={false} /></Form.Item><Row gutter={[16, 16]}><Col xs={24} sm={12}><Form.Item name="quantity" label="Quantity" rules={[{ required: true }]}><InputNumber min={0.001} precision={3} style={{ width: '100%' }} /></Form.Item></Col><Col xs={24} sm={12}><Form.Item name="totalCost" label="Total cost" rules={[{ required: true }]}><InputNumber min={0} precision={2} prefix="$" style={{ width: '100%' }} /></Form.Item></Col></Row><Form.Item name="purchaseDate" label="Date" rules={[{ required: true }]}><DatePicker style={{ width: '100%' }} /></Form.Item><Form.Item name="expenseCategoryId" label="Expense category (optional)"><Select allowClear options={[]} style={{ width: '100%' }} /></Form.Item><Form.Item name="paymentMethodId" label="Payment method (optional)"><Select allowClear options={[]} style={{ width: '100%' }} /></Form.Item><Form.Item name="notes" label="Notes"><Input.TextArea rows={2} /></Form.Item></Form></Modal>
  </Card>;
}; export default SuppliersPage;
