namespace FMS.Application.Animal;

/// <summary>
/// One entry of a batch creation.
///
/// The id is supplied by the caller rather than generated by the service, because
/// it is what lets rows inside a single batch reference each other — a calf's dam
/// may be another row of the same file, and that reference has to be resolvable
/// before anything is written.
/// </summary>
public class BulkAnimalCreateItem
{
    public Guid Id { get; set; }
    public CreateAnimalRequest Request { get; set; } = new();
}

/// <summary>
/// A batch failure, reported by the item's position in the batch so the caller can
/// point at its own row.
/// </summary>
public class BulkAnimalCreateFailureDto
{
    public int Index { get; set; }
    public string Message { get; set; } = string.Empty;
}

public class BulkAnimalCreateResultDto
{
    public int RequestedCount { get; set; }
    public int SuccessCount { get; set; }
    public List<BulkAnimalCreateFailureDto> Failures { get; set; } = new();
}
