import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { offlineShell } from './vite-plugin-offline.ts';

/**
 * The build-time half of the offline shell: what the plugin does to a real output
 * directory. The generated worker's contents are asserted in
 * `src/offline/swTemplate.test.ts`; what matters here is that the manifest comes from
 * what was actually written, and that a build which cannot serve the shell fails
 * instead of shipping.
 */

const created: string[] = [];

const makeOutDir = (files: Record<string, string>): string => {
  const dir = mkdtempSync(join(tmpdir(), 'fms-offline-'));
  created.push(dir);

  for (const [name, contents] of Object.entries(files)) {
    const full = join(dir, name);
    mkdirSync(join(full, '..'), { recursive: true });
    writeFileSync(full, contents, 'utf8');
  }

  return dir;
};

/** Runs the plugin's write phase against a directory, with the same hook surface Vite gives it. */
const runWriteBundle = (outDir: string, options: { buildSha?: string } = {}): string => {
  const plugin = offlineShell(options);
  const context = {
    error: (message: string) => {
      throw new Error(message);
    },
    info: () => undefined,
  };

  (plugin.configResolved as (config: unknown) => void)({
    base: '/FarmManagementSystem/',
    root: outDir,
    build: { outDir },
  });

  (plugin.writeBundle as (this: unknown) => void).call(context);
  return readFileSync(join(outDir, 'sw.js'), 'utf8');
};

afterEach(() => {
  while (created.length > 0) {
    rmSync(created.pop()!, { recursive: true, force: true });
  }
});

describe('offline shell build step', () => {
  it('precaches what the build actually wrote', () => {
    const outDir = makeOutDir({
      'index.html': '<div id="root"></div>',
      'favicon.svg': '<svg />',
      'assets/app-abc123.js': 'console.log(1)',
      'assets/app-abc123.js.map': '{}',
    });

    const source = runWriteBundle(outDir);

    expect(source).toContain('/FarmManagementSystem/index.html');
    expect(source).toContain('/FarmManagementSystem/assets/app-abc123.js');
    expect(source).toContain('/FarmManagementSystem/favicon.svg');
    // Not the source map, and never the worker itself.
    expect(source).not.toContain('.js.map');
    expect(source).not.toContain('"sw.js"');
  });

  /// A worker with no shell installs cleanly and then does nothing useful offline. The
  /// build must stop instead, which is the only moment anyone can notice.
  it('fails the build when the shell is missing', () => {
    const outDir = makeOutDir({ 'assets/app-abc123.js': 'console.log(1)' });

    expect(() => runWriteBundle(outDir)).toThrow(/index\.html/);
  });

  it('does not precache a worker left over from a previous build', () => {
    const outDir = makeOutDir({
      'index.html': '<div id="root"></div>',
      'assets/app-abc123.js': 'console.log(1)',
      'sw.js': 'stale worker from a previous build',
    });

    const source = runWriteBundle(outDir);

    expect(source).toContain('Generated by tools/offline/vite-plugin-offline.ts');
    expect(source).not.toContain('stale worker from a previous build');
  });

  it('versions the cache by the deployment sha when the build has one', () => {
    const outDir = makeOutDir({
      'index.html': '<div id="root"></div>',
      'assets/app-abc123.js': 'console.log(1)',
    });

    expect(runWriteBundle(outDir, { buildSha: 'deadbee' })).toContain('"deadbee"');
  });
});
